/** Declaration file generated by dts-gen */

export function getOr(strPath: any, defaultValue: any): any;

export function remap(mapping: any, source: any, context: any): any;

export function remapArray(strPath: any, mapping: any): any;

export function remapFrom(strPath: any, mapping: any): any;

export function withChild(strPath: any, fn: any): any;

